library(dplyr)
library(usethis)

# dev/web.archive.org/web/20230607181247/https%3A/tylervigen.com/spurious-correlations

spurious_correlations <- list()

spurious_correlations[[1]] <- tibble(
    year = 1999:2009,
    var1 = "US spending on science, space, and technology",
    var2 = "Suicides by hanging, strangulation and suffocation",
    var1_short = "US spending on science",
    var2_short = "Suicides",
    var1_unit = "billion",
    var2_unit = "suicides",
    var1_value = c(18.079, 18.594, 19.753, 20.734, 20.831, 23.029, 23.597, 23.584, 25.525, 27.731, 29.449),
    var2_value = c(5427, 5688, 6198, 6462, 6635, 7336, 7248, 7491, 8161, 8578, 9000),
    source = "U.S. Office of Management and Budget and Centers for Disease Control & Prevention"
)

spurious_correlations[[2]] <- tibble(
    year = 1999:2009,
    var1 = "Number of people who drowned by falling into a pool",
    var2 = "Films Nicolas Cage appeared in",
    var1_short = "Falling into a pool drownings",
    var2_short = "Nicholas Cage",
    var1_unit = "drownings",
    var2_unit = "films",
    var1_value = c(109, 102, 102, 98, 85, 95, 96, 98, 123, 94, 102),
    var2_value = c(2, 2, 2, 3, 1, 1, 2, 3, 4, 1, 4),
    source = "Centers for Disease Control & Prevention and Internet Movie spurious_correlationsbase"
)

spurious_correlations[[3]] <- tibble(
    year = 2000:2009,
    var1 = "Per capita cheese consumption",
    var2 = "Number of people who died by becoming tangled in their bedsheets",
    var1_short = "Cheese consumed",
    var2_short = "Bedsheet tanglings",
    var1_unit = "lbs",
    var2_unit = "deaths",
    var1_value = c(29.8, 30.1, 30.5, 30.6, 31.3, 31.7, 32.6, 33.1, 32.7, 32.8),
    var2_value = c(327, 456, 509, 497, 596, 573, 661, 741, 809, 717),
    source = "U.S. Department of Agriculture and Centers for Disease Control & Prevention"
)

spurious_correlations[[4]] <- tibble(
    year = 2000:2009,
    var1 = "Divorce rate in Maine",
    var2 = "Per capita consumption of margarine",
    var1_short = "Divorce rate in Maine",
    var2_short = "Margarine consumed",
    var1_unit = "per 1,000",
    var2_unit = "lbs",
    var1_value = c(5, 4.7, 4.6, 4.4, 4.3, 4.1, 4.2, 4.2, 4.2, 4.1),
    var2_value = c(8.2, 7, 6.5, 5.3, 5.2, 4, 4.6, 4.5, 4.2, 3.7),
    source = "National Vital Statistics Reports and U.S. Department of Agriculture"
)

spurious_correlations[[5]] <- tibble(
    year = 1999:2009,
    var1 = "Age of Miss America",
    var2 = "Murders by steam, hot vapours and hot objects",
    var1_short = "Age of Miss America",
    var2_short = "Murders by steam",
    var1_unit = "years",
    var2_unit = "murders",
    var1_value = c(24, 24, 24, 21, 22, 21, 24, 22, 20, 19, 22),
    var2_value = c(7, 7, 7, 3, 4, 3, 8, 4, 2, 3, 2),
    source = "Wikipedia and Centers for Disease Control & Prevention"
)

spurious_correlations[[6]] <- tibble(
    year = 2000:2009,
    var1 = "Total revenue generated by arcades",
    var2 = "Computer science doctorates awarded in the US",
    var1_short = "Arcade revenue",
    var2_short = "Computer science doctorates",
    var1_unit = "billion",
    var2_unit = "degrees",
    var1_value = c(1.196, 1.176, 1.269, 1.240, 1.307, 1.435, 1.601, 1.654, 1.803, 1.734),
    var2_value = c(861, 830, 809, 867, 948, 1129, 1453, 1656, 1787, 1611),
    source = "U.S. Census Bureau and National Science Foundation"
)

spurious_correlations[[7]] <- tibble(
    year = 1997:2009,
    var1 = "Worldwide non-commercial space launches",
    var2 = "Sociology doctorates awarded in the US",
    var1_short = "Space launches",
    var2_short = "Sociology doctorates",
    var1_unit = "launches",
    var2_unit = "degrees",
    var1_value = c(54, 46, 42, 50, 43, 41, 46, 39, 37, 45, 45, 41, 54),
    var2_value = c(601, 579, 572, 617, 566, 547, 597, 580, 536, 579, 576, 601, 664),
    source = "National Science Foundation and Federal Aviation Administration"
)

spurious_correlations[[8]] <- tibble(
    year = 2000:2009,
    var1 = "Per capita consumption of mozzarella cheese",
    var2 = "Civil engineering doctorates awarded in the US",
    var1_short = "Mozzarella cheese consumption",
    var2_short = "Engineering doctorates",
    var1_unit = "lbs",
    var2_unit = "degrees",
    var1_value = c(9.3, 9.7, 9.7, 9.7, 9.9, 10.2, 10.5, 11, 10.6, 10.6),
    var2_value = c(480, 501, 540, 552, 547, 622, 655, 701, 712, 708),
    source = "National Science Foundation and U.S. Department of Agriculture"
)

spurious_correlations[[9]] <- tibble(
    year = 1999:2010,
    var1 = "People who drowned after falling out of a fishing boat",
    var2 = "Marriage rate in Kentucky",
    var1_short = "Fishing boat deaths",
    var2_short = "Kentucky marriages",
    var1_unit = "deaths",
    var2_unit = "per 1,000",
    var1_value = c(19, 16, 9, 12, 15, 10, 11, 7, 2, 5, 1, 1),
    var2_value = c(10.9, 9.8, 9, 9, 9.1, 8.8, 8.7, 8.4, 7.8, 7.9, 7.6, 7.4),
    source = "Centers for Disease Control & Prevention and National Vital Statistics Report"
)

spurious_correlations[[10]] <- tibble(
    year = 1999:2009,
    var1 = "US crude oil imports from Norway",
    var2 = "Drivers killed in collision with railway train",
    var1_short = "US crude oil imports from Norway",
    var2_short = "Railway train collisions",
    var1_unit = "million barrels",
    var2_unit = "deaths",
    var1_value = c(96, 110, 103, 127, 60, 54, 43, 36, 20, 11, 22),
    var2_value = c(76, 74, 76, 87, 66, 59, 63, 60, 55, 52, 46),
    source = "Center for Disease Control & Prevention and Dept. of Energy"
)

spurious_correlations[[11]] <- tibble(
    year = 2000:2009,
    var1 = "Per capita consumption of chicken",
    var2 = "Total US crude oil imports",
    var1_short = "Chicken consumption",
    var2_short = "US crude oil imports",
    var1_unit = "lbs",
    var2_unit = "billion barrels",
    var1_value = c(54.2, 54, 56.8, 57.5, 59.3, 60.5, 60.9, 59.9, 58.7, 56),
    var2_value = c(3.311, 3.405, 3.336, 3.521, 3.674, 3.670, 3.685, 3.656, 3.571, 3.307),
    source = "Dept. of Energy and U.S. Department of Agriculture"
)

spurious_correlations[[12]] <- tibble(
    year = 1999:2009,
    var1 = "Number of people who drowned while in a swimming-pool",
    var2 = "Power generated by US nuclear plants",
    var1_short = "Swimming pool drownings",
    var2_short = "Nuclear power plants",
    var1_unit = "deaths",
    var2_unit = "billion kWh",
    var1_value = c(421, 465, 494, 538, 430, 530, 511, 600, 582, 605, 603),
    var2_value = c(728.3, 753.9, 768.8, 780.1, 763.7, 788.5, 782, 787.2, 806.4, 806.2, 798.9),
    source = "Centers for Disease Control & Prevention and Dept. of Energy"
)

spurious_correlations[[13]] <- tibble(
    year = 1999:2009,
    var1 = "Japanese cars sold in the US",
    var2 = "Suicides by crashing of motor vehicle",
    var1_short = "Japanese cars sold",
    var2_short = "Suicides by crashing",
    var1_unit = "thousand cars",
    var2_unit = "suicides",
    var1_value = c(758, 863, 837, 930, 830, 810, 923, 1154, 1183, 1142, 829),
    var2_value = c(87, 103, 91, 112, 104, 108, 113, 137, 131, 129, 104),
    source = "Centers for Disease Control & Prevention and U.S Bureau of Transportation Statistics"
)

spurious_correlations[[14]] <- tibble(
    year = 1999:2009,
    var1 = "Letters in the winning word of the Scripps National Spelling Bee",
    var2 = "Number of people killed by venomous spiders",
    var1_short = "Spelling bee letters",
    var2_short = "Spider deaths",
    var1_unit = "letters",
    var2_unit = "deaths",
    var1_value = c(9, 8, 11, 12, 11, 13, 12, 9, 9, 7, 9),
    var2_value = c(6, 5, 5, 10, 8, 14, 10, 4, 8, 5, 6),
    source = "Centers for Disease Control & Prevention and National Spelling Bee"
)

spurious_correlations[[15]] <- tibble(
    year = 1996:2008,
    var1 = "Mathematics doctorates awarded",
    var2 = "Uranium stored at nuclear power plants",
    var1_short = "Math doctorates",
    var2_short = "Uranium stored",
    var1_unit = "degrees",
    var2_unit = "million lbs",
    var1_value = c(1122, 1123, 1177, 1083, 1050, 1010, 919, 993, 1076, 1205, 1325, 1393, 1399),
    var2_value = c(66.1, 65.9, 65.8, 58.3, 54.8, 55.6, 53.5, 45.6, 57.7, 64.7, 77.5, 81.2, 81.9),
    source = "National Science Foundation and Dept. of Energy"
)

spurious_correlations <- bind_rows(spurious_correlations) %>%
    mutate_if(is.character, as.factor)

use_data(spurious_correlations, overwrite = TRUE)

use_cc0_license()

writexl::write_xlsx(spurious_correlations, "dev/spurious_correlations.xlsx")
