#' @title 'US spending on science, space, and technology' correlates with
#'  'Suicides by hanging, strangulation and suffocation'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.992.
#' 
#' @source U.S. Office of Management and Budget and Centers for Disease Control & Prevention
#'
#' @format A tibbles with 11 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{US spending on science, space, and technology (USD billion)}
#'  \item{y}{Suicides by hanging, strangulation and suffocation}
#' }
"us_spending"

#' @title 'Number of people who drowned by falling into a pool' correlates with
#'  'Films Nicolas Cage appeared in'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.666.
#' 
#' @source Centers for Disease Control & Prevention and Internet Movie Database
#'
#' @format A tibbles with 11 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{Number of people who drowned by falling into a pool}
#'  \item{y}{Films Nicolas Cage appeared in}
#' }
"pool_drownings"

#' @title 'Per capita cheese consumption' correlates with
#'  'Number of people who died by becoming tangled in their bedsheets'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.947.
#' 
#' @source U.S. Department of Agriculture and Centers for Disease Control & Prevention
#'
#' @format A tibbles with 10 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{Per capita cheese consumption (lbs)}
#'  \item{y}{Number of people who died by becoming tangled in their bedsheets}
#' }
"cheese_consumption"

#' @title 'Divorce rate in Maine' correlates with
#'  'Per capita consumption of margarine'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.992.
#' 
#' @source National Vital Statistics Reports and U.S. Department of Agriculture
#'
#' @format A tibbles with 10 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{Divorce rate in Maine (per 1,000)}
#'  \item{y}{Per capita consumption of margarine (lbs)}
#' }
"divorce_rate_maine"

#' @title 'Age of Miss America' correlates with
#'  'Murders by steam, hot vapours and hot objects'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.870.
#' 
#' @source Wikipedia and Centers for Disease Control & Prevention
#'
#' @format A tibbles with 11 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{Age of Miss America}
#'  \item{y}{Murders by steam, hot vapours and hot objects}
#' }
"miss_america_age"

#' @title 'Total revenue generated by arcades' correlates with
#'  'Computer science doctorates awarded in the US'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.985.
#' 
#' @source U.S. Census Bureau and National Science Foundation
#'
#' @format A tibbles with 10 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{Total revenue generated by arcades (USD billion)}
#'  \item{y}{Computer science doctorates awarded in the US}
#' }
"arcade_revenue"

#' @title 'Worldwide non-commercial space launches' correlates with
#'  'Sociology doctorates awarded in the US'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.789.
#' 
#' @source National Science Foundation and Federal Aviation Administration
#'
#' @format A tibbles with 13 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{Worldwide non-commercial space launches}
#'  \item{y}{Sociology doctorates awarded in the US}
#' }
"space_launches"

#' @title 'Per capita consumption of mozzarella cheese' correlates with
#'  'Civil engineering doctorates awarded in the US'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.959.
#' 
#' @source National Science Foundation and U.S. Department of Agriculture
#'
#' @format A tibbles with 10 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{Per capita consumption of mozzarella cheese (lbs)}
#'  \item{y}{Civil engineering doctorates awarded in the US}
#' }
"mozzarella_consumption"

#' @title 'People who drowned after falling out of a fishing boat' correlates with
#'  'Marriage rate in Kentucky'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.952.
#' 
#' @source Centers for Disease Control & Prevention and National Vital Statistics Report
#'
#' @format A tibbles with 12 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{People who drowned after falling out of a fishing boat}
#'  \item{y}{Marriage rate in Kentucky (per 1,000)}
#' }
"fishing_boat_drownings"

#' @title 'US crude oil imports from Norway' correlates with
#'  'Drivers killed in collision with railway train'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.955.
#' 
#' @source Center for Disease Control & Prevention and Dept. of Energy
#'
#' @format A tibbles with 11 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{US crude oil imports from Norway (million barrels)}
#'  \item{y}{Drivers killed in collision with railway train}
#' }
"norway_oil_imports"

#' @title 'Per capita consumption of chicken' correlates with
#'  'Total US crude oil imports'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.899.
#' 
#' @source Dept. of Energy and U.S. Department of Agriculture
#'
#' @format A tibbles with 10 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{Per capita consumption of chicken (lbs)}
#'  \item{y}{Total US crude oil imports (billion barrels)}
#' }
"chicken_consumption"

#' @title 'Number of people who drowned while in a swimming-pool' correlates with
#'  'Power generated by US nuclear plants'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.901.
#' 
#' @source Centers for Disease Control & Prevention and Dept. of Energy
#'
#' @format A tibbles with 11 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{Number of people who drowned while in a swimming-pool}
#'  \item{y}{Power generated by US nuclear plants (billion kWh)}
#' }
"swimming_pool_drownings"

#' @title 'Japanese cars sold in the US' correlates with
#'  'Suicides by crashing of motor vehicle'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.934.
#' 
#' @source Centers for Disease Control & Prevention and U.S Bureau of Transportation Statistics
#'
#' @format A tibbles with 11 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{Japanese cars sold in the US (thousand cars)}
#'  \item{y}{Suicides by crashing of motor vehicle}
#' }
"japanese_cars_sold"

#' @title 'Letters in the winning word of the Scripps National Spelling Bee' correlates with
#'  'Number of people killed by venomous spiders'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.805.
#' 
#' @source Centers for Disease Control & Prevention and National Spelling Bee
#'
#' @format A tibbles with 11 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{Letters in the winning word of the Scripps National Spelling Bee}
#'  \item{y}{Number of people killed by venomous spiders}
#' }
"spelling_bee_letters"

#' @title 'Mathematics doctorates awarded' correlates with
#'  'Uranium stored at nuclear power plants'
#'
#' @description A dataset to preserve tylervigen.com correlations. The correlation
#'  is 0.952.
#' 
#' @source National Science Foundation and Dept. of Energy
#'
#' @format A tibbles with 13 observations and 3 variables:
#' \describe{
#'  \item{year}{Year}
#'  \item{x}{Mathematics doctorates awarded}
#'  \item{y}{Uranium stored at nuclear power plants (million lbs)}
#' }
"math_doctorates"
